Step7
kiras0518/rails_crud pull request #3
Opened 2018-07-13 09:54 UTC by kiras0518

### 步驟7: 讓任務能夠被新增、修改、刪除

- 製作任務的列表、新增、檢視、修改頁面
- 以 rails generate 指令產生 controller
- 請和導師討論要用哪一種 template engine
- 實做 controller 和 view 必要的部分
- 新增、修改、刪除後，需要顯示對應的 flash 訊息
- 修改 routes.rb，讓 http://localhost:3000/ 會顯示任務的列表頁面
- 在 GitHub 上發 PR 並請人 review
- 之後的 PR，如果覺得過於龐大，就需要開始考慮分割成多個 PR

2018-07-16 09:36 UTC, YushengLi requested changes
似乎有一些應該要清除的東西沒有清掉，如果有需要幫助的話，歡迎再約時間來問

2018-07-16 09:36 UTC, YushengLi commented on app/controllers/candidates_controller.rb
> +    def task_params
這邊為什麼會出現 CandidateController? 作用是？

2018-07-16 09:36 UTC, YushengLi commented on app/controllers/tasks_controller.rb
> +        @task = Task.find_by(id: params[:id])
這邊的話我會喜歡用 `Task.find(params[:id])`，找不到對應的 Task 的時候，ActiveRecord 會直接 Raise `ActiveRecord::RecordNotFound`，Rails 這邊就可以接住然後渲染 404 找不到頁面。

2018-07-16 09:36 UTC, YushengLi commented on app/controllers/tasks_controller.rb
> +      params.require(:task).permit(:tilte, :context, :status, :end_date)
`priority` 沒有在白名單裡面，是因為刻意不給在這個 Controller 更新嗎？

2018-07-16 09:36 UTC, YushengLi commented on app/views/candidates/index.html.erb
> +            <<td><%= link_to "+1測試", vote_candidate_path(candidate), method: "post", data: { confirm: "確認要+1嗎?!" }, class:"btn btn-warning btn-xs" %></td>
好像多了一個 `<`

2018-07-16 09:36 UTC, YushengLi commented on db/migrate/20180713063230_rename_table.rb
> +class RenameTable < ActiveRecord::Migration[5.2]
理論上這邊不應該有 Drop Table 的 Migration，這個 Migration 的作用是？

2018-07-16 09:36 UTC, YushengLi commented on db/schema.rb
>    create_table "candidates", force: :cascade do |t|
這邊 Candidate Table 的作用是？似乎不是這個任務要求的一部分？

2018-07-16 09:39 UTC, YushengLi commented
另外因為 Rails 的 Generator 預設會幫忙長出一整串東西，包含 Style, JS (Coffee), Helper, Spec, Fixture 等，如果沒有用到的話其實可以直接移掉，等到需要的時候再自己長出來就好，這樣翻程式碼的時候才不會翻到一堆空白的檔案。

2018-07-16 09:41 UTC, YushengLi commented
另外這個 PR 有很多的 Comments，一般來說我們會盡可能把 Code 撰寫的簡單易懂到不需要 Comments 的地步會更好，一般來說，好的 Comments 應該是紀錄「為什麼這樣做」、而不是「做了什麼」。

另外因為有用 Git 的關係，所以不要的 Code 其實可以直接移除，不用特地用 Comment 留下來。

2018-07-16 09:42 UTC, YushengLi commented
有需要討論的，歡迎再隨時敲時間 :)

2018-07-17 07:20 UTC, kiras0518 commented on app/controllers/candidates_controller.rb
> +    def task_params
Candidate 是當初練習所創建的

2018-07-17 07:24 UTC, kiras0518 commented on app/views/candidates/index.html.erb
> +            <<td><%= link_to "+1測試", vote_candidate_path(candidate), method: "post", data: { confirm: "確認要+1嗎?!" }, class:"btn btn-warning btn-xs" %></td>
已修正，感謝提醒

2018-07-17 07:25 UTC, kiras0518 commented on db/migrate/20180713063230_rename_table.rb
> +class RenameTable < ActiveRecord::Migration[5.2]
當初是練習DB 修改 Migration
刪除某個欄位使用

2018-07-20 08:30 UTC, merged