步驟13: 網站佈署
kiras0518/rails_crud pull request #5
Opened 2018-07-24 08:04 UTC by kiras0518

- 一般版（非 DevOps 適用）
- 來將 master branch 上的簡易任務管理系統推上線吧
- 試著將網站 deploy 到 Heroku 上
- 沒有帳號的話，請建立帳號
- 戳一下被推上 Heroku 的網站
- 接下來就會在這裡建立任務並繼續開發
- ※ 不過，推上 Heroku 後，就是在網路上公開了，請注意不要放敏感資料
- 現階段，或許可以考慮加入 basic 認證
- 今後，每個步驟完成後，就繼續將成品推上 Heroku
- 將佈署的方法寫進 README.md
- 也將使用的 framework 版號等資料記下來

2018-07-24 08:21 UTC, ccmikechen commented
先把 #4 merge完在發PR

2018-07-24 09:21 UTC, ccmikechen commented on Gemfile
> +  gem 'pg'
這邊`group :production do`裡面放`gem 'pg'`表示你在production上用的DB是用postgresql，但你Gemfile上面已經有一個放在外面的`gem 'pg'`，這表示你在任何環境都是用postgresql，所以就不用在`group :production do`裡面在放一個了。

2018-07-24 09:28 UTC, ccmikechen commented on Gemfile
> +ruby '2.3.3'
這邊改2.3.3的目的是？

2018-07-24 10:00 UTC, taiansu requested changes
不一定要用 rails 內建這麼 magic 的方法，但是要考慮到改動 enum 時會造成選項不一致的情況。i.e. single source of truth.

2018-07-24 10:00 UTC, taiansu commented on app/views/tasks/_form.html.erb
> +        <%= f.select :status ,['pending','handling','finished']%>
應該可以靠 `Task.statuses` 拿到 keys of enum.

2018-07-24 11:06 UTC, kiras0518 commented on Gemfile
> +  gem 'pg'
了解

2018-07-25 06:01 UTC, kiras0518 commented on Gemfile
> +ruby '2.3.3'
測試CI顯示錯誤訊息
"Your Ruby version is 2.5.1, but your Gemfile specified 2.3.3"

2018-07-26 07:43 UTC, kiras0518 commented on app/views/tasks/_form.html.erb
> +        <%= f.select :status ,['pending','handling','finished']%>
長知識 查到有這種寫法

2018-07-26 08:05 UTC, kiras0518 commented
OK

2018-07-26 18:23 UTC, taiansu approved these changes
Doesn't meant to be the road block.

2018-07-30 02:31 UTC, merged